version = 1

test_patterns = ["**/*_test.go"]

[[analyzers]]
name = "docker"
enabled = true

[[analyzers]]
name = "go"
enabled = true

  [analyzers.meta]
  import_root = "github.com/burntcarrot/k8sensus"

[[analyzers]]
name = "shell"
enabled = true

[[transformers]]
name = "gofmt"
enabled = true